name: Keep Streamlit Alive

on:
  schedule:
    # Spouští se automaticky každých 6 hodin
    - cron: '0 */6 * * *'
  workflow_dispatch: # Umožňuje spustit testovací "ping" i ručně

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s https://lceckoapp-frs3fyslxu6w44nfvhcwls.streamlit.app/ > /dev/null
